version: '3.6'

services:
  api:
    image: quay.io/go-skynet/local-ai:master
    restart: unless-stopped
    ports:
      - '8080:8080'
    env_file:
      - .env
    volumes:
      - ./models:/models:cached
    command: ["/usr/bin/local-ai"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/models"]
      interval: 30s
      timeout: 10s
      retries: 3
  frontend:
    image: quay.io/go-skynet/localai-frontend:master
    env_file:
      - .env
    ports:
      - 3000:3000
    restart: unless-stopped
